# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://ncyubrd.github.io
title: 嘉義大學生物資源學系
email: biors@mail.ncyu.edu.tw
author: Cheng-Tao Lin
description: > 
  嘉義大學生物資源學系
copyright: '2017 Department of Biological Resources'
credits: 'Credits: original jekyll theme was designed by <a href="https://github.com/swcool">Shane Weng</a>. Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
comments: true

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook
    url: https://www.facebook.com/groups/148437755234370

  - title: github
    url: https://github.com/ncyubrd
#  - title: flickr
#    url: http://flickr.com/mutolisp
